# Site settings 配置站点
title: 'nycko'
description: 'description'
keyword: 'key, word'
url: 'http://nycko.github.io' # your host

# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# Navigation links
nav:
  home: ''
  tags: '/tags.html'
  
# Author 配置博主信息
author: 'NyckoBen'
nickname: 'Nycko'
bio: 'C/C++攻城狮 爱生活 爱折腾'
avatar: '/assets/img/profile.png'

# Search
search: true

# Night mode
nightMode: false

# Comments 评论
#disqus: false
#disqus_url: 'https://liaokeyu.disqus.com/embed.js'

# MathJax 公式支持 by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ['wechat', 'weibo']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站
# url: weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  weibo: '//weibo.com/nycko'
#  juejin: '//juejin.im/user/57a6f434165abd006159b4cc'
#  instagram: '//www.instagram.com/steveliaocn'
#  github: '//github.com/kaeyleo'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown

highlighter: rouge

kramdown:
  input: GFM
#  use_coderay: true
#  
#  coderay:
#    coderay_wrap: div
#    coderay_line_numbers: inline
#    coderay_line_numbers_start: 1
#    coderay_tab_width: 4
#    coderay_bold_every: 10
#    coderay_css: style

# RSS  
RSS: false

# Plugins
plugins: [jekyll-paginate]

baidu-analysis: 52bc94134779e020ff4f58ad9ff1a486
